#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Preprocess InteriorNet mask clips + captions into FastVideo TI2V+ControlNet parquet.

This mirrors the core encoding logic in:
  fastvideo/pipelines/preprocess/v1_preprocess_omnigame_ti2v_controlnet.py

Input layout (MASK_INTERIORNET):
  <mask_root>/<scene_key>/<window_start>_<window_end>/clip_start_XXX/
      mask/*.png
      masked_rgb/*.png   (optional; if missing, will fall back to rgb * mask)
      caption_*.json     (generated by tools/qwen_caption_interiornet_clips.py)

RGB/Depth layout (DATA_INTERIORNET):
  <data_root>/<HD>/<SCENE_ID>/<SEQ>/cam0/data/*.(webp|png|jpg)
  <data_root>/<HD>/<SCENE_ID>/<SEQ>/depth0/data/*.(png|exr)

Alignment convention (same as our caption script / UniDataset loader intent):
  global_idx = window_start + clip_start + local_idx
where local_idx is 0..clip_length-1.

Output:
  <output_dir>/rank_XX/worker_*/data_chunk_*.parquet compatible with
  fastvideo.dataset.dataloader.schema.py: pyarrow_schema_ti2v_controlnet
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
from pathlib import Path
from typing import Any

import ftfy
import imageio.v2 as imageio
import numpy as np
import torch
from PIL import Image
from tqdm import tqdm

from fastvideo import PipelineConfig
from fastvideo.dataset.dataloader.parquet_io import ParquetDatasetWriter, records_to_table
from fastvideo.dataset.dataloader.schema import pyarrow_schema_ti2v_controlnet
from fastvideo.fastvideo_args import FastVideoArgs
from fastvideo.logger import init_logger
from fastvideo.models.loader.component_loader import PipelineComponentLoader
from fastvideo.pipelines.stages.text_encoding import TextEncodingStage

logger = init_logger(__name__)


def _prompt_clean(text: str) -> str:
    text = ftfy.fix_text(str(text))
    text = html.unescape(html.unescape(text))
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _read_caption_json(path: Path, caption_key: str) -> str:
    obj = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(obj, dict) and "captions" in obj and isinstance(obj["captions"], dict):
        caps = obj["captions"]
    else:
        caps = obj

    if caption_key:
        v = caps.get(caption_key, "")
        if isinstance(v, str) and v.strip():
            return v.strip()

    # fallback order
    for k in ("Video_Caption", "Short_Caption", "PC_Caption", "caption", "text", "prompt", "description"):
        v = caps.get(k, "")
        if isinstance(v, str) and v.strip():
            return v.strip()
    return ""


def _resize_for_crop_pil(img: Image.Image, crop_h: int, crop_w: int) -> Image.Image:
    img_w, img_h = img.size
    if (img_h >= crop_h and img_w >= crop_w) or (img_h <= crop_h and img_w <= crop_w):
        coef = max(crop_h / img_h, crop_w / img_w)
    else:
        coef = crop_h / img_h if crop_h > img_h else crop_w / img_w
    out_h, out_w = int(img_h * coef), int(img_w * coef)
    img = img.resize((out_w, out_h), resample=Image.BICUBIC)
    left = max(0, (out_w - crop_w) // 2)
    top = max(0, (out_h - crop_h) // 2)
    return img.crop((left, top, left + crop_w, top + crop_h))


def _load_rgb_frame(path: Path, height: int, width: int) -> torch.Tensor:
    img = Image.open(path).convert("RGB")
    img = _resize_for_crop_pil(img, crop_h=int(height), crop_w=int(width))
    arr = np.asarray(img).astype(np.float32) / 255.0
    return torch.from_numpy(arr).permute(2, 0, 1).contiguous()  # 3HW in [0,1]


def _load_mask_frame(path: Path, height: int, width: int, *, threshold: float | None) -> torch.Tensor:
    img = Image.open(path).convert("L")
    arr_u8 = np.asarray(img).astype(np.uint8)

    h0, w0 = arr_u8.shape[:2]
    target_ratio = float(width) / float(height)
    current_ratio = float(w0) / float(h0)
    if current_ratio > target_ratio:
        new_w = int(h0 * target_ratio)
        left = max(0, (w0 - new_w) // 2)
        arr_u8 = arr_u8[:, left:left + new_w]
    else:
        new_h = int(w0 / target_ratio)
        top = max(0, (h0 - new_h) // 2)
        arr_u8 = arr_u8[top:top + new_h, :]

    arr_u8 = np.array(Image.fromarray(arr_u8).resize((int(width), int(height)), resample=Image.NEAREST))
    arr = arr_u8.astype(np.float32) / 255.0
    if threshold is not None:
        arr = (arr > float(threshold)).astype(np.float32)
    t = torch.from_numpy(arr)[None, ...].repeat(3, 1, 1).contiguous()  # 3HW in [0,1]
    return t


def _read_depth_any(path: Path) -> np.ndarray:
    # Supports uint16 png depth (often mm) and float exr.
    arr = imageio.imread(path)
    if arr.ndim == 3:
        arr = arr[..., 0]
    return arr.astype(np.float32)


def _load_depth_sequence(depth_paths: list[Path], height: int, width: int, *, pmin: float, pmax: float) -> torch.Tensor:
    """
    Convert metric-ish depth to ControlNet depth conditioning:
      - center crop to aspect, resize NEAREST
      - normalize with global percentiles (pmin..pmax) across the clip
      - invert (near -> 1, far -> 0)
      - invalid pixels set to -1
    Returns: (T,3,H,W) float32.
    """
    target_ratio = float(width) / float(height)
    depths: list[np.ndarray] = []
    for p in depth_paths:
        d = _read_depth_any(p)

        h0, w0 = d.shape
        current_ratio = float(w0) / float(h0)
        if current_ratio > target_ratio:
            new_w = int(h0 * target_ratio)
            left = max(0, (w0 - new_w) // 2)
            d = d[:, left:left + new_w]
        else:
            new_h = int(w0 / target_ratio)
            top = max(0, (h0 - new_h) // 2)
            d = d[top:top + new_h, :]

        d = np.array(Image.fromarray(d).resize((int(width), int(height)), resample=Image.NEAREST)).astype(np.float32)

        # Heuristic: InteriorNet depth png is often millimeters.
        if np.nanmax(d) > 100.0:
            d = d / 1000.0

        valid = np.isfinite(d) & (d > 1e-6)
        d[~valid] = np.nan
        depths.append(d)

    stacked = np.stack(depths, axis=0)
    valid_vals = stacked[np.isfinite(stacked)]
    if valid_vals.size == 0:
        lo, hi = 0.0, 1.0
    else:
        lo = float(np.percentile(valid_vals, pmin))
        hi = float(np.percentile(valid_vals, pmax))
        if not np.isfinite(lo) or not np.isfinite(hi) or (hi - lo) < 1e-6:
            lo, hi = float(np.nanmin(valid_vals)), float(np.nanmax(valid_vals))
            if not np.isfinite(lo) or not np.isfinite(hi) or (hi - lo) < 1e-6:
                lo, hi = 0.0, 1.0

    out = []
    denom = max(hi - lo, 1e-6)
    for d in depths:
        dn = (d - lo) / denom
        dn = np.clip(dn, 0.0, 1.0)
        dn = 1.0 - dn
        dn = np.nan_to_num(dn, nan=-1.0)
        t = torch.from_numpy(dn).float().unsqueeze(0).repeat(3, 1, 1)
        out.append(t)
    return torch.stack(out, dim=0)  # T,3,H,W


def _to_vae_input(video_tchw: torch.Tensor, *, normalize: bool) -> torch.Tensor:
    # (T,3,H,W) -> (1,3,T,H,W)
    x = video_tchw.unsqueeze(0).permute(0, 2, 1, 3, 4).contiguous()
    if normalize:
        x = x * 2.0 - 1.0
    return x


def _postprocess_vae_latents(vae, latents: torch.Tensor) -> torch.Tensor:
    if hasattr(vae, "shift_factor") and vae.shift_factor is not None:
        shift = vae.shift_factor
        if isinstance(shift, torch.Tensor):
            shift = shift.to(latents.device, latents.dtype)
        latents = latents - shift
    scale = getattr(vae, "scaling_factor", None)
    if scale is not None:
        if isinstance(scale, torch.Tensor):
            scale = scale.to(latents.device, latents.dtype)
        latents = latents * scale
    return latents


@torch.no_grad()
def _encode_video_latents(vae, video_bcthw: torch.Tensor, *, sample_mode: str) -> torch.Tensor:
    with torch.autocast(
        device_type="cuda",
        dtype=torch.float32,
        enabled=torch.cuda.is_available() and video_bcthw.is_cuda,
    ):
        out = vae.encode(video_bcthw)
    if sample_mode == "mode":
        latents = out.mode()
    elif sample_mode == "sample":
        latents = out.sample()
    else:
        raise ValueError(f"Unsupported sample_mode: {sample_mode}")
    return _postprocess_vae_latents(vae, latents)


def _infer_latent_repeat(model_path: str, z_dim: int) -> int:
    cfg_path = Path(model_path) / "transformer" / "config.json"
    if not cfg_path.exists():
        return 1
    try:
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    except Exception:
        return 1
    in_channels = cfg.get("in_channels")
    if isinstance(in_channels, (int, float)):
        in_channels = int(in_channels)
        if in_channels > 0 and in_channels % int(z_dim) == 0:
            return in_channels // int(z_dim)
    return 1


def _list_caption_files(clip_dir: Path, pattern: str) -> list[Path]:
    return sorted([p for p in clip_dir.glob(pattern) if p.is_file()], key=lambda p: p.name)


def _pick_indexed_files(files: dict[int, Path], length: int) -> list[Path]:
    """
    Given a sparse mapping {idx -> path}, return a dense list of size `length`.
    Missing indices are filled by nearest available <= idx, otherwise nearest > idx.
    """
    if not files:
        raise ValueError("Empty files map")
    available = sorted(files.keys())
    out: list[Path] = []
    for i in range(length):
        if i in files:
            out.append(files[i])
            continue
        # nearest <= i
        j = None
        for a in reversed(available):
            if a <= i:
                j = a
                break
        if j is None:
            j = available[0]
        out.append(files[j])
    return out


def _parse_scene_key(scene_key: str) -> tuple[str, str, str]:
    parts = scene_key.split("_", 2)
    if len(parts) < 3:
        raise ValueError(f"Invalid scene key: {scene_key}")
    return parts[0], parts[1], parts[2]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser("Preprocess InteriorNet clips to TI2V+ControlNet parquet")
    p.add_argument("--model_path", type=str, required=True, help="Wan diffusers root (contains text_encoder/vae/etc)")
    p.add_argument("--mask_root", type=str, required=True, help="MASK_INTERIORNET root.")
    p.add_argument("--data_root", type=str, required=True, help="DATA_INTERIORNET root.")
    p.add_argument("--output_dir", type=str, required=True, help="Output parquet dataset directory.")
    p.add_argument("--rank", type=int, default=0, help="Shard rank (0-based).")
    p.add_argument("--world_size", type=int, default=1, help="Number of shards.")
    p.add_argument("--scene_key", type=str, default="", help="Optional single scene key to process.")
    p.add_argument("--clip_length", type=int, default=81, help="Number of RGB frames per clip.")
    p.add_argument("--fps", type=int, default=16, help="FPS metadata.")
    p.add_argument("--max_width", type=int, default=512)
    p.add_argument("--max_height", type=int, default=384)
    p.add_argument("--mask_threshold", type=float, default=0.5, help="Binarization threshold; set <0 to keep soft.")
    p.add_argument("--depth_percentile_min", type=float, default=5.0)
    p.add_argument("--depth_percentile_max", type=float, default=95.0)
    p.add_argument("--caption_pattern", type=str, default="caption*.json")
    p.add_argument("--caption_key", type=str, default="Video_Caption", help="Which field under captions{} to use as prompt.")
    p.add_argument("--samples_per_file", type=int, default=8)
    p.add_argument("--flush_frequency", type=int, default=8)
    p.add_argument("--device", type=str, default="cuda", choices=["cuda", "cpu"])
    p.add_argument("--dtype", type=str, default="bf16", choices=["bf16", "fp16", "fp32"])
    p.add_argument("--latent_repeat", type=int, default=0, help="0=auto; 1=keep; 3=repeat 3x,...")
    p.add_argument("--strict_window_len", action="store_true", help="Require window dirs to have exactly --window_len frames.")
    p.add_argument("--window_len", type=int, default=243)
    p.add_argument(
        "--first_frame_source",
        type=str,
        default="rgb",
        choices=["rgb", "masked_rgb"],
        help="Which source to encode as first_frame_latent. "
        "'rgb' uses InteriorNet cam0/data. 'masked_rgb' uses clip_dir/masked_rgb.",
    )
    p.add_argument(
        "--require_masked_rgb",
        action="store_true",
        help="If set, require clip_dir/masked_rgb to exist. "
        "When missing, skip the clip (no rgb*mask fallback).",
    )
    return p.parse_args()


def main() -> None:
    os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

    args = parse_args()
    if int(args.world_size) <= 0:
        raise ValueError("--world_size must be >= 1")
    if int(args.rank) < 0 or int(args.rank) >= int(args.world_size):
        raise ValueError(f"--rank must be in [0,{int(args.world_size)-1}]")

    model_path = os.path.expanduser(os.path.expandvars(args.model_path))
    mask_root = Path(os.path.expanduser(os.path.expandvars(args.mask_root)))
    data_root = Path(os.path.expanduser(os.path.expandvars(args.data_root)))
    output_dir = Path(os.path.expanduser(os.path.expandvars(args.output_dir)))
    output_dir.mkdir(parents=True, exist_ok=True)

    # Device setup
    if args.device == "cuda" and torch.cuda.is_available():
        device = torch.device("cuda")
        torch.cuda.set_device(device)
    else:
        device = torch.device("cpu")

    # Pipeline config + modules (same as v1_preprocess_omnigame_ti2v_controlnet.py)
    pipeline_config = PipelineConfig.from_pretrained(model_path)
    fastvideo_args = FastVideoArgs(
        model_path=model_path,
        num_gpus=1,
        dit_cpu_offload=False,
        vae_cpu_offload=False,
        text_encoder_cpu_offload=False,
        pipeline_config=pipeline_config,
    )

    text_encoder = PipelineComponentLoader.load_module(
        module_name="text_encoder",
        component_model_path=os.path.join(model_path, "text_encoder"),
        transformers_or_diffusers="transformers",
        fastvideo_args=fastvideo_args,
    ).to(device)
    tokenizer = PipelineComponentLoader.load_module(
        module_name="tokenizer",
        component_model_path=os.path.join(model_path, "tokenizer"),
        transformers_or_diffusers="transformers",
        fastvideo_args=fastvideo_args,
    )
    vae = PipelineComponentLoader.load_module(
        module_name="vae",
        component_model_path=os.path.join(model_path, "vae"),
        transformers_or_diffusers="diffusers",
        fastvideo_args=fastvideo_args,
    ).to(device)

    text_stage = TextEncodingStage(text_encoders=[text_encoder], tokenizers=[tokenizer])

    z_dim = getattr(vae, "z_dim", None)
    if z_dim is None:
        z_dim = getattr(getattr(vae, "config", None), "z_dim", None)
    if z_dim is None:
        z_dim = 16
    if int(args.latent_repeat) > 0:
        latent_repeat = int(args.latent_repeat)
    else:
        latent_repeat = _infer_latent_repeat(model_path, int(z_dim))
    latent_repeat = max(1, int(latent_repeat))

    # Output writer per rank
    out_dir_rank = output_dir / f"rank_{int(args.rank):02d}"
    writer = ParquetDatasetWriter(str(out_dir_rank), samples_per_file=int(args.samples_per_file))
    buffer: list[dict[str, Any]] = []

    scene_dirs = [mask_root / args.scene_key] if args.scene_key else [p for p in sorted(mask_root.iterdir()) if p.is_dir()]
    # Build flat clip list and shard by rank/world_size for stable partitioning.
    all_clips: list[Path] = []
    for scene_dir in scene_dirs:
        for window_dir in sorted(scene_dir.iterdir()):
            if not window_dir.is_dir() or "_" not in window_dir.name:
                continue
            for clip_dir in sorted(window_dir.iterdir()):
                if clip_dir.is_dir() and clip_dir.name.startswith("clip_start_"):
                    all_clips.append(clip_dir)

    clips = [p for i, p in enumerate(all_clips) if (i % int(args.world_size)) == int(args.rank)]
    pbar = tqdm(clips, desc=f"interiornet->parquet[r{args.rank}/{args.world_size}]")

    for clip_dir in pbar:
        window_dir = clip_dir.parent
        scene_dir = window_dir.parent
        scene_key = scene_dir.name

        try:
            window_start_str, window_end_str = window_dir.name.split("_", 1)
            window_start = int(window_start_str)
            window_end = int(window_end_str)
        except Exception:
            logger.warning("Skip invalid window dir: %s", window_dir)
            continue

        if bool(args.strict_window_len):
            if (window_end - window_start + 1) != int(args.window_len):
                continue

        try:
            clip_start = int(clip_dir.name.split("_")[-1])
        except Exception:
            logger.warning("Skip invalid clip dir: %s", clip_dir)
            continue

        cap_files = _list_caption_files(clip_dir, str(args.caption_pattern))
        if not cap_files:
            continue
        cap_path = cap_files[-1]
        prompt = _prompt_clean(_read_caption_json(cap_path, str(args.caption_key)))
        if not prompt:
            continue

        hd, scene_id, seq_id = _parse_scene_key(scene_key)
        cam_dir = data_root / hd / scene_id / seq_id / "cam0" / "data"
        depth_dir = data_root / hd / scene_id / seq_id / "depth0" / "data"
        if not depth_dir.is_dir():
            continue

        # NOTE: For some workflows we intentionally avoid using the original RGB.
        # We still keep cam_dir available for fallback (when masked_rgb is missing),
        # or when first_frame_source=rgb.
        rgb_files: list[Path] | None = None
        if cam_dir.is_dir():
            rgb_files = sorted([p for p in cam_dir.iterdir() if p.is_file()], key=lambda p: p.name)

        depth_files = sorted([p for p in depth_dir.iterdir() if p.is_file()], key=lambda p: p.name)
        if not depth_files:
            continue

        # Build dense per-frame paths for this clip (with clamp).
        clip_global_start = window_start + clip_start
        if bool(args.strict_window_len):
            if (clip_global_start + int(args.clip_length) - 1) > (window_start + int(args.window_len) - 1):
                continue

        global_indices = [clip_global_start + t for t in range(int(args.clip_length))]
        depth_paths = [depth_files[min(max(gi, 0), len(depth_files) - 1)] for gi in global_indices]

        # Load mask/masked_rgb from clip dir; allow sparse indices by nearest-fill.
        mask_dir = clip_dir / "mask"
        if not mask_dir.is_dir():
            continue
        mask_files_map: dict[int, Path] = {}
        for p in mask_dir.iterdir():
            if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp"):
                if p.stem.isdigit():
                    mask_files_map[int(p.stem)] = p
        if not mask_files_map:
            continue
        mask_paths = _pick_indexed_files(mask_files_map, int(args.clip_length))

        masked_rgb_dir = clip_dir / "masked_rgb"
        masked_rgb_paths: list[Path] | None = None
        if masked_rgb_dir.is_dir():
            mr_map: dict[int, Path] = {}
            for p in masked_rgb_dir.iterdir():
                if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp"):
                    if p.stem.isdigit():
                        mr_map[int(p.stem)] = p
            if mr_map:
                masked_rgb_paths = _pick_indexed_files(mr_map, int(args.clip_length))
        if bool(args.require_masked_rgb) and masked_rgb_paths is None:
            continue

        # ---- text embedding (float32 [L,D]) ----
        embeds_list = text_stage.encode_text(
            prompt,
            fastvideo_args=fastvideo_args,
            encoder_index=0,
            return_attention_mask=False,
            return_type="list",
            device=device,
            dtype=torch.float32,
        )
        text_emb = embeds_list[0]
        if text_emb.ndim == 3:
            text_emb = text_emb[0]
        text_emb = text_emb.detach().to("cpu", dtype=torch.float32).numpy()

        # ---- first frame latent ----
        if str(args.first_frame_source) == "masked_rgb":
            if masked_rgb_paths is None:
                # Only possible when require_masked_rgb is False.
                if not rgb_files:
                    continue
                rgb_paths = [rgb_files[min(max(gi, 0), len(rgb_files) - 1)] for gi in global_indices]
                first_rgb = _load_rgb_frame(rgb_paths[0], int(args.max_height), int(args.max_width))
            else:
                first_rgb = _load_rgb_frame(masked_rgb_paths[0], int(args.max_height), int(args.max_width))
        else:
            if not rgb_files:
                continue
            rgb_paths = [rgb_files[min(max(gi, 0), len(rgb_files) - 1)] for gi in global_indices]
            first_rgb = _load_rgb_frame(rgb_paths[0], int(args.max_height), int(args.max_width))
        first_bcthw = _to_vae_input(first_rgb[None, ...], normalize=True).to(device=device, dtype=torch.float32)
        first_lat = _encode_video_latents(vae, first_bcthw, sample_mode="mode")
        if latent_repeat != 1:
            first_lat = first_lat.repeat(1, latent_repeat, 1, 1, 1)
        first_lat = first_lat[0, :, 0].unsqueeze(0)  # 1,C,H,W
        first_lat_np = first_lat.to("cpu", dtype=torch.float32).numpy()

        # ---- control latents (depth, masked_rgb, mask) ----
        depth_tchw = _load_depth_sequence(
            depth_paths,
            int(args.max_height),
            int(args.max_width),
            pmin=float(args.depth_percentile_min),
            pmax=float(args.depth_percentile_max),
        )
        mask_tchw = torch.stack(
            [
                _load_mask_frame(
                    p,
                    int(args.max_height),
                    int(args.max_width),
                    threshold=None if float(args.mask_threshold) < 0 else float(args.mask_threshold),
                )
                for p in mask_paths
            ],
            dim=0,
        )
        if masked_rgb_paths is not None:
            masked_rgb_tchw = torch.stack(
                [_load_rgb_frame(p, int(args.max_height), int(args.max_width)) for p in masked_rgb_paths],
                dim=0,
            )
        else:
            if bool(args.require_masked_rgb):
                continue
            if not rgb_files:
                continue
            rgb_paths = [rgb_files[min(max(gi, 0), len(rgb_files) - 1)] for gi in global_indices]
            rgb_tchw = torch.stack([_load_rgb_frame(p, int(args.max_height), int(args.max_width)) for p in rgb_paths], dim=0)
            masked_rgb_tchw = rgb_tchw * mask_tchw

        video_n = torch.cat(
            [
                _to_vae_input(depth_tchw, normalize=False),
                _to_vae_input(masked_rgb_tchw, normalize=True),
                _to_vae_input(mask_tchw, normalize=False),
            ],
            dim=0,
        ).to(device=device, dtype=torch.float32)
        lat_n = _encode_video_latents(vae, video_n, sample_mode="mode").to("cpu", dtype=torch.float32)
        depth_lat = lat_n[0]
        masked_lat = lat_n[1]
        mask_lat = lat_n[2]
        if latent_repeat != 1:
            depth_lat = depth_lat.repeat(latent_repeat, 1, 1, 1)
            masked_lat = masked_lat.repeat(latent_repeat, 1, 1, 1)
            mask_lat = mask_lat.repeat(latent_repeat, 1, 1, 1)
        control_lat = torch.cat([depth_lat, masked_lat, mask_lat], dim=0)
        control_lat_np = control_lat.numpy()

        empty_lat = np.zeros((0,), dtype=np.float32)
        record_id = f"{scene_key}/{window_dir.name}/{clip_dir.name}"
        record = {
            "id": record_id,
            "text_embedding_bytes": text_emb.tobytes(),
            "text_embedding_shape": list(text_emb.shape),
            "text_embedding_dtype": "float32",
            "vae_latent_bytes": empty_lat.tobytes(),
            "vae_latent_shape": [],
            "vae_latent_dtype": "",
            "first_frame_latent_bytes": first_lat_np.tobytes(),
            "first_frame_latent_shape": list(first_lat_np.shape),
            "first_frame_latent_dtype": "float32",
            "control_latent_bytes": control_lat_np.tobytes(),
            "control_latent_shape": list(control_lat_np.shape),
            "control_latent_dtype": "float32",
            "file_name": record_id,
            "caption": prompt,
            "media_type": "video",
            "width": int(args.max_width),
            "height": int(args.max_height),
            "num_frames": int(control_lat_np.shape[1]) if len(control_lat_np.shape) > 1 else 0,
            "duration_sec": float(int(args.clip_length)) / float(args.fps) if int(args.fps) > 0 else 0.0,
            "fps": float(args.fps),
        }
        buffer.append(record)

        if len(buffer) >= int(args.flush_frequency):
            table = records_to_table(buffer, pyarrow_schema_ti2v_controlnet)
            writer.append_table(table)
            writer.flush(num_workers=1, write_remainder=False)
            buffer = []

    if buffer:
        table = records_to_table(buffer, pyarrow_schema_ti2v_controlnet)
        writer.append_table(table)
        writer.flush(num_workers=1, write_remainder=True)

    logger.info("Done. Wrote parquet dataset to: %s (rank shard: %s)", output_dir, out_dir_rank)


if __name__ == "__main__":
    main()
