#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Preprocess MatrixCity mask clips + captions into FastVideo TI2V+ControlNet parquet.

Input layout (MASK_MATRIXCITY):
  <mask_root>/<street_dir>/<window_start>_<window_end>/clip_start_XXX/
      mask/*.png
      masked_rgb/*.png   (optional; if missing, will fall back to rgb * mask)
      caption_*.json     (generated by a Qwen caption script)

RGB layout (DATA_MATRIXCITY, RGB only):
  <rgb_root>/small_city/street/<street_split>/<street_dir>/<street_dir>/*.png

Depth layout options:
  1) If you have a "small_city_depth" dataset (EXR), pass --depth_root pointing to the
     root that contains "small_city_depth/..." and we will try to locate the aligned
     depth folder. (EXR decoding requires OpenCV EXR enabled.)
  2) If you already have per-frame depth PNGs aligned to RGB, you can point --depth_dir
     directly to that folder and skip auto-derivation.

Window interpretation:
  - If window_start/window_end are valid indices into the sorted RGB list, treat as index range.
  - Otherwise, treat as "frame id range" (stems); this script will slice by id.

If the window range is shorter than needed (common in MatrixCity masks), the script pads by
repeating the last frame, matching the dataset's typical padding behavior.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
from pathlib import Path
from typing import Any

import ftfy
import imageio.v2 as imageio
import numpy as np
import torch
import pyarrow.parquet as pq
from PIL import Image
from tqdm import tqdm

from fastvideo import PipelineConfig
from fastvideo.dataset.dataloader.parquet_io import ParquetDatasetWriter, records_to_table
from fastvideo.dataset.dataloader.schema import pyarrow_schema_ti2v_controlnet
from fastvideo.distributed.parallel_state import (
    maybe_init_distributed_environment_and_model_parallel,
)
from fastvideo.fastvideo_args import FastVideoArgs
from fastvideo.logger import init_logger
from fastvideo.models.loader.component_loader import PipelineComponentLoader
from fastvideo.pipelines.stages.text_encoding import TextEncodingStage

logger = init_logger(__name__)


def _load_existing_ids(parquet_rank_dir: Path) -> set[str]:
    ids: set[str] = set()
    if not parquet_rank_dir.is_dir():
        return ids
    for pf in sorted(parquet_rank_dir.rglob("*.parquet")):
        try:
            table = pq.read_table(str(pf), columns=["id"])
            col = table.column("id").to_pylist()
            for x in col:
                if x is not None:
                    ids.add(str(x))
        except Exception as e:
            logger.warning("Failed to read existing ids from %s: %s", pf, e)
    return ids


def _prompt_clean(text: str) -> str:
    text = ftfy.fix_text(str(text))
    text = html.unescape(html.unescape(text))
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _read_caption_json(path: Path, caption_key: str) -> str:
    obj = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(obj, dict) and "captions" in obj and isinstance(obj["captions"], dict):
        caps = obj["captions"]
    else:
        caps = obj

    if caption_key:
        v = caps.get(caption_key, "")
        if isinstance(v, str) and v.strip():
            return v.strip()

    for k in ("Video_Caption", "Short_Caption", "PC_Caption", "caption", "text", "prompt", "description"):
        v = caps.get(k, "")
        if isinstance(v, str) and v.strip():
            return v.strip()
    return ""


def _resize_for_crop_pil(img: Image.Image, crop_h: int, crop_w: int) -> Image.Image:
    img_w, img_h = img.size
    if (img_h >= crop_h and img_w >= crop_w) or (img_h <= crop_h and img_w <= crop_w):
        coef = max(crop_h / img_h, crop_w / img_w)
    else:
        coef = crop_h / img_h if crop_h > img_h else crop_w / img_w
    out_h, out_w = int(img_h * coef), int(img_w * coef)
    img = img.resize((out_w, out_h), resample=Image.BICUBIC)
    left = max(0, (out_w - crop_w) // 2)
    top = max(0, (out_h - crop_h) // 2)
    return img.crop((left, top, left + crop_w, top + crop_h))


def _load_rgb_frame(path: Path, height: int, width: int) -> torch.Tensor:
    img = Image.open(path).convert("RGB")
    img = _resize_for_crop_pil(img, crop_h=int(height), crop_w=int(width))
    arr = np.asarray(img).astype(np.float32) / 255.0
    return torch.from_numpy(arr).permute(2, 0, 1).contiguous()


def _load_mask_frame(path: Path, height: int, width: int, *, threshold: float | None) -> torch.Tensor:
    img = Image.open(path).convert("L")
    arr_u8 = np.asarray(img).astype(np.uint8)
    h0, w0 = arr_u8.shape[:2]
    target_ratio = float(width) / float(height)
    current_ratio = float(w0) / float(h0)
    if current_ratio > target_ratio:
        new_w = int(h0 * target_ratio)
        left = max(0, (w0 - new_w) // 2)
        arr_u8 = arr_u8[:, left:left + new_w]
    else:
        new_h = int(w0 / target_ratio)
        top = max(0, (h0 - new_h) // 2)
        arr_u8 = arr_u8[top:top + new_h, :]
    arr_u8 = np.array(Image.fromarray(arr_u8).resize((int(width), int(height)), resample=Image.NEAREST))
    arr = arr_u8.astype(np.float32) / 255.0
    if threshold is not None:
        arr = (arr > float(threshold)).astype(np.float32)
    return torch.from_numpy(arr)[None, ...].repeat(3, 1, 1).contiguous()


def _read_depth_any(path: Path) -> np.ndarray:
    if path.suffix.lower() == ".exr":
        try:
            import cv2  # lazy import; EXR requires OpenCV built with EXR support

            arr = cv2.imread(str(path), cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
            if arr is None:
                raise FileNotFoundError(path)
            if arr.ndim == 3:
                arr = arr[..., 0]
            return arr.astype(np.float32)
        except Exception:
            # fallback to imageio
            pass
    arr = imageio.imread(path)
    if arr.ndim == 3:
        arr = arr[..., 0]
    return arr.astype(np.float32)


def _load_depth_sequence(depth_paths: list[Path], height: int, width: int, *, pmin: float, pmax: float) -> torch.Tensor:
    target_ratio = float(width) / float(height)
    depths: list[np.ndarray] = []
    for p in depth_paths:
        d = _read_depth_any(p)
        h0, w0 = d.shape
        current_ratio = float(w0) / float(h0)
        if current_ratio > target_ratio:
            new_w = int(h0 * target_ratio)
            left = max(0, (w0 - new_w) // 2)
            d = d[:, left:left + new_w]
        else:
            new_h = int(w0 / target_ratio)
            top = max(0, (h0 - new_h) // 2)
            d = d[top:top + new_h, :]
        d = np.array(Image.fromarray(d).resize((int(width), int(height)), resample=Image.NEAREST)).astype(np.float32)

        # Heuristic: if depth looks like centimeters or millimeters, scale down.
        mx = float(np.nanmax(d)) if np.isfinite(d).any() else 0.0
        if mx > 1000.0:
            d = d / 1000.0
        elif mx > 100.0:
            d = d / 100.0

        valid = np.isfinite(d) & (d > 1e-6)
        d[~valid] = np.nan
        depths.append(d)

    stacked = np.stack(depths, axis=0)
    valid_vals = stacked[np.isfinite(stacked)]
    if valid_vals.size == 0:
        lo, hi = 0.0, 1.0
    else:
        lo = float(np.percentile(valid_vals, pmin))
        hi = float(np.percentile(valid_vals, pmax))
        if not np.isfinite(lo) or not np.isfinite(hi) or (hi - lo) < 1e-6:
            lo, hi = float(np.nanmin(valid_vals)), float(np.nanmax(valid_vals))
            if not np.isfinite(lo) or not np.isfinite(hi) or (hi - lo) < 1e-6:
                lo, hi = 0.0, 1.0

    out = []
    denom = max(hi - lo, 1e-6)
    for d in depths:
        dn = (d - lo) / denom
        dn = np.clip(dn, 0.0, 1.0)
        dn = 1.0 - dn
        dn = np.nan_to_num(dn, nan=-1.0)
        t = torch.from_numpy(dn).float().unsqueeze(0).repeat(3, 1, 1)
        out.append(t)
    return torch.stack(out, dim=0)


def _to_vae_input(video_tchw: torch.Tensor, *, normalize: bool) -> torch.Tensor:
    x = video_tchw.unsqueeze(0).permute(0, 2, 1, 3, 4).contiguous()
    if normalize:
        x = x * 2.0 - 1.0
    return x


def _postprocess_vae_latents(vae, latents: torch.Tensor) -> torch.Tensor:
    if hasattr(vae, "shift_factor") and vae.shift_factor is not None:
        shift = vae.shift_factor
        if isinstance(shift, torch.Tensor):
            shift = shift.to(latents.device, latents.dtype)
        latents = latents - shift
    scale = getattr(vae, "scaling_factor", None)
    if scale is not None:
        if isinstance(scale, torch.Tensor):
            scale = scale.to(latents.device, latents.dtype)
        latents = latents * scale
    return latents


@torch.no_grad()
def _encode_video_latents(vae, video_bcthw: torch.Tensor, *, sample_mode: str) -> torch.Tensor:
    with torch.autocast(device_type="cuda", dtype=torch.float32, enabled=torch.cuda.is_available() and video_bcthw.is_cuda):
        out = vae.encode(video_bcthw)
    if sample_mode == "mode":
        latents = out.mode()
    elif sample_mode == "sample":
        latents = out.sample()
    else:
        raise ValueError(f"Unsupported sample_mode: {sample_mode}")
    return _postprocess_vae_latents(vae, latents)


def _infer_latent_repeat(model_path: str, z_dim: int) -> int:
    cfg_path = Path(model_path) / "transformer" / "config.json"
    if not cfg_path.exists():
        return 1
    try:
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    except Exception:
        return 1
    in_channels = cfg.get("in_channels")
    if isinstance(in_channels, (int, float)):
        in_channels = int(in_channels)
        if in_channels > 0 and in_channels % int(z_dim) == 0:
            return in_channels // int(z_dim)
    return 1


def _list_caption_files(clip_dir: Path, pattern: str) -> list[Path]:
    return sorted([p for p in clip_dir.glob(pattern) if p.is_file()], key=lambda p: p.name)


def _pick_indexed_files(files: dict[int, Path], length: int) -> list[Path]:
    if not files:
        raise ValueError("Empty files map")
    available = sorted(files.keys())
    out: list[Path] = []
    for i in range(length):
        if i in files:
            out.append(files[i])
            continue
        # nearest <= i
        j = None
        for a in reversed(available):
            if a <= i:
                j = a
                break
        if j is None:
            j = available[0]
        out.append(files[j])
    return out


def _sorted_pngs(dir_path: Path) -> list[Path]:
    files = [p for p in dir_path.iterdir() if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp", ".bmp")]
    # Prefer integer-stem sort when possible
    if files and all(p.stem.isdigit() for p in files):
        return sorted(files, key=lambda p: int(p.stem))
    return sorted(files, key=lambda p: p.name)


def _sorted_depth_files(dir_path: Path) -> list[Path]:
    files = [
        p
        for p in dir_path.iterdir()
        if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp", ".bmp", ".exr")
    ]
    if files and all(p.stem.isdigit() for p in files):
        return sorted(files, key=lambda p: int(p.stem))
    return sorted(files, key=lambda p: p.name)


def _slice_by_id_or_index(files: list[Path], start: int, end: int) -> list[Path]:
    if not files:
        return []
    n = len(files)
    # index-range
    if 0 <= start <= end < n:
        return files[start:end + 1]
    # id-range
    if all(p.stem.isdigit() for p in files):
        ids = [int(p.stem) for p in files]
        lo = None
        hi = None
        # find first >= start and last <= end
        for i, fid in enumerate(ids):
            if lo is None and fid >= start:
                lo = i
            if fid <= end:
                hi = i
        if lo is not None and hi is not None and lo <= hi:
            return files[lo:hi + 1]
    return []


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser("Preprocess MatrixCity clips to TI2V+ControlNet parquet")
    p.add_argument("--model_path", type=str, required=True)
    p.add_argument("--mask_root", type=str, required=True)
    p.add_argument("--rgb_root", type=str, required=True, help="MatrixCity RGB root (contains small_city/...).")
    p.add_argument(
        "--depth_root",
        type=str,
        default="",
        help=(
            "Optional MatrixCity depth root (contains small_city_depth/...). "
            "If not set, defaults to --rgb_root."
        ),
    )
    p.add_argument("--output_dir", type=str, required=True)
    p.add_argument(
        "--normal_root",
        type=str,
        default="",
        help=(
            "Optional normal root. If set, script tries "
            "<normal_root>/<street>/<window>/<clip>/normal first, then "
            "<normal_root>/<street>/<window>/<clip>."
        ),
    )
    p.add_argument(
        "--require_normal",
        action="store_true",
        help="If set, only keep clips with valid normal frames (4-part control latent).",
    )
    p.add_argument("--rank", type=int, default=0)
    p.add_argument("--world_size", type=int, default=1)
    p.add_argument("--street_split", type=str, default="train_dense_half", help="train_dense_half/train_dense/test")
    p.add_argument("--street_dir", type=str, default="", help="Optional single street_dir to process (e.g. small_city_road_down_dense).")
    p.add_argument("--clip_length", type=int, default=81)
    p.add_argument("--window_len", type=int, default=243, help="Pad each window to at least this many frames by repeating last.")
    p.add_argument(
        "--first_frame_source",
        type=str,
        default="rgb",
        choices=["rgb", "masked_rgb"],
        help="Which source to encode as first_frame_latent. "
        "'rgb' uses the RGB sequence under --rgb_root. "
        "'masked_rgb' uses clip_dir/masked_rgb.",
    )
    p.add_argument(
        "--require_masked_rgb",
        action="store_true",
        help="If set, require clip_dir/masked_rgb to exist. "
        "When missing, skip the clip (no rgb*mask fallback).",
    )
    p.add_argument("--fps", type=int, default=16)
    p.add_argument("--max_width", type=int, default=512)
    p.add_argument("--max_height", type=int, default=384)
    p.add_argument("--mask_threshold", type=float, default=0.5)
    p.add_argument("--depth_dir", type=str, default="", help="Optional direct depth directory aligned to rgb (png/exr).")
    p.add_argument("--depth_percentile_min", type=float, default=5.0)
    p.add_argument("--depth_percentile_max", type=float, default=95.0)
    p.add_argument("--caption_pattern", type=str, default="caption*.json")
    p.add_argument("--caption_key", type=str, default="Video_Caption")
    p.add_argument("--samples_per_file", type=int, default=8)
    p.add_argument("--flush_frequency", type=int, default=8)
    p.add_argument(
        "--max_samples",
        type=int,
        default=0,
        help="Stop after writing this many samples. 0 means no limit.",
    )
    p.add_argument(
        "--max_samples_global",
        action="store_true",
        help=(
            "When used with --max_samples and world_size>1, apply the limit globally "
            "by letting rank0 process all clips (other ranks stay idle)."
        ),
    )
    p.add_argument("--device", type=str, default="cuda", choices=["cuda", "cpu"])
    p.add_argument("--dtype", type=str, default="bf16", choices=["bf16", "fp16", "fp32"])
    p.add_argument("--latent_repeat", type=int, default=0)
    p.add_argument(
        "--write_vae_latent",
        action="store_true",
        help=(
            "If set, encode RGB clip and write non-empty vae_latent fields. "
            "Required for AR-TF phase-1 training."
        ),
    )
    p.add_argument(
        "--skip_existing_ids",
        action="store_true",
        help="Resume-friendly mode: skip records whose id already exists in output parquet rank shard.",
    )
    return p.parse_args()


def main() -> None:
    os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
    os.environ.setdefault("OPENCV_IO_ENABLE_OPENEXR", "1")

    args = parse_args()
    env_world_size = int(os.environ.get("WORLD_SIZE", "1"))
    env_rank = int(os.environ.get("RANK", "0"))
    env_local_rank = int(os.environ.get("LOCAL_RANK", "0"))
    # Support torchrun: when user does not explicitly pass rank/world_size,
    # inherit from distributed env vars.
    if env_world_size > 1:
        if int(args.world_size) == 1:
            args.world_size = env_world_size
        if int(args.rank) == 0:
            args.rank = env_rank

    if int(args.world_size) <= 0:
        raise ValueError("--world_size must be >= 1")
    if int(args.rank) < 0 or int(args.rank) >= int(args.world_size):
        raise ValueError(f"--rank must be in [0,{int(args.world_size)-1}]")

    model_path = os.path.expanduser(os.path.expandvars(args.model_path))
    mask_root = Path(os.path.expanduser(os.path.expandvars(args.mask_root)))
    rgb_root = Path(os.path.expanduser(os.path.expandvars(args.rgb_root)))
    depth_root = Path(os.path.expanduser(os.path.expandvars(args.depth_root))) if str(args.depth_root).strip() else rgb_root
    output_dir = Path(os.path.expanduser(os.path.expandvars(args.output_dir)))
    normal_root = Path(os.path.expanduser(os.path.expandvars(args.normal_root))) if str(args.normal_root).strip() else None
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.device == "cuda" and torch.cuda.is_available():
        # torchrun: use LOCAL_RANK; manual CUDA_VISIBLE_DEVICES per process: local rank defaults to 0.
        device = torch.device(f"cuda:{env_local_rank}")
        torch.cuda.set_device(env_local_rank)

        # Some FastVideo layers (e.g., vocab-parallel embedding) expect TP/SP groups
        # to be initialized even in single-process mode.
        # torchrun mode: use env:// shared rendezvous.
        # standalone per-process mode: use unique tcp:// port per shard.
        if env_world_size > 1:
            dist_init_method = "env://"
        else:
            dist_port = 29500 + int(args.rank)
            dist_init_method = f"tcp://127.0.0.1:{dist_port}"
        maybe_init_distributed_environment_and_model_parallel(
            tp_size=1,
            sp_size=1,
            distributed_init_method=dist_init_method,
        )
    else:
        device = torch.device("cpu")

    pipeline_config = PipelineConfig.from_pretrained(model_path)
    fastvideo_args = FastVideoArgs(
        model_path=model_path,
        num_gpus=1,
        dit_cpu_offload=False,
        vae_cpu_offload=False,
        text_encoder_cpu_offload=False,
        pipeline_config=pipeline_config,
    )

    text_encoder = PipelineComponentLoader.load_module(
        module_name="text_encoder",
        component_model_path=os.path.join(model_path, "text_encoder"),
        transformers_or_diffusers="transformers",
        fastvideo_args=fastvideo_args,
    ).to(device)
    tokenizer = PipelineComponentLoader.load_module(
        module_name="tokenizer",
        component_model_path=os.path.join(model_path, "tokenizer"),
        transformers_or_diffusers="transformers",
        fastvideo_args=fastvideo_args,
    )
    vae = PipelineComponentLoader.load_module(
        module_name="vae",
        component_model_path=os.path.join(model_path, "vae"),
        transformers_or_diffusers="diffusers",
        fastvideo_args=fastvideo_args,
    ).to(device)
    text_stage = TextEncodingStage(text_encoders=[text_encoder], tokenizers=[tokenizer])

    z_dim = getattr(vae, "z_dim", None)
    if z_dim is None:
        z_dim = getattr(getattr(vae, "config", None), "z_dim", None)
    if z_dim is None:
        z_dim = 16
    latent_repeat = int(args.latent_repeat) if int(args.latent_repeat) > 0 else _infer_latent_repeat(model_path, int(z_dim))
    latent_repeat = max(1, int(latent_repeat))

    out_dir_rank = output_dir / f"rank_{int(args.rank):02d}"
    writer = ParquetDatasetWriter(str(out_dir_rank), samples_per_file=int(args.samples_per_file))
    buffer: list[dict[str, Any]] = []
    existing_ids: set[str] = set()
    if bool(args.skip_existing_ids):
        existing_ids = _load_existing_ids(out_dir_rank)
        logger.info(
            "Resume mode enabled: found %d existing ids in %s",
            len(existing_ids),
            out_dir_rank,
        )

    street_dirs = [mask_root / args.street_dir] if args.street_dir else [p for p in sorted(mask_root.iterdir()) if p.is_dir()]
    all_clips: list[Path] = []
    for street_dir in street_dirs:
        for window_dir in sorted(street_dir.iterdir()):
            if not window_dir.is_dir() or "_" not in window_dir.name:
                continue
            for clip_dir in sorted(window_dir.iterdir()):
                if clip_dir.is_dir() and clip_dir.name.startswith("clip_start_"):
                    all_clips.append(clip_dir)

    if int(args.max_samples) > 0 and bool(args.max_samples_global) and int(
            args.world_size) > 1:
        if int(args.rank) == 0:
            clips = list(all_clips)
            logger.info(
                "Using global max_samples=%d across all ranks via rank0-only processing.",
                int(args.max_samples),
            )
        else:
            clips = []
    else:
        clips = [
            p for i, p in enumerate(all_clips)
            if (i % int(args.world_size)) == int(args.rank)
        ]
    if bool(args.skip_existing_ids) and existing_ids:
        before = len(clips)
        clips = [
            p
            for p in clips
            if f"{p.parent.parent.name}/{p.parent.name}/{p.name}" not in existing_ids
        ]
        logger.info(
            "Resume filter on rank_%02d: %d -> %d clips (skipped %d existing)",
            int(args.rank),
            before,
            len(clips),
            before - len(clips),
        )
    pbar = tqdm(clips,
                desc=f"matrixcity->parquet[r{args.rank}/{args.world_size}]")
    written_count = 0

    for clip_dir in pbar:
        window_dir = clip_dir.parent
        street_dir = window_dir.parent
        street_name = street_dir.name

        try:
            w_start_str, w_end_str = window_dir.name.split("_", 1)
            window_start = int(w_start_str)
            window_end = int(w_end_str)
        except Exception:
            continue
        try:
            clip_start = int(clip_dir.name.split("_")[-1])
        except Exception:
            continue

        cap_files = _list_caption_files(clip_dir, str(args.caption_pattern))
        if not cap_files:
            continue
        prompt = _prompt_clean(_read_caption_json(cap_files[-1], str(args.caption_key)))
        if not prompt:
            continue

        rgb_dir = rgb_root / "small_city" / "street" / str(args.street_split) / street_name / street_name
        if not rgb_dir.is_dir():
            continue
        rgb_files = _sorted_pngs(rgb_dir)
        if not rgb_files:
            continue

        # Optional depth dir
        depth_files: list[Path] | None = None
        if str(args.depth_dir).strip():
            ddir = Path(os.path.expanduser(os.path.expandvars(str(args.depth_dir).strip())))
            if ddir.is_dir():
                depth_files = _sorted_depth_files(ddir)
        else:
            # Auto-derive depth dir from MatrixCity layout used in UniDataset:
            # small_city_depth/street/<split>/<street>_depth/<street>_depth/*.exr
            auto_depth_dir = (
                depth_root
                / "small_city_depth"
                / "street"
                / str(args.street_split)
                / f"{street_name}_depth"
                / f"{street_name}_depth"
            )
            if auto_depth_dir.is_dir():
                depth_files = _sorted_depth_files(auto_depth_dir)

        window_files = _slice_by_id_or_index(rgb_files, window_start, window_end)
        if not window_files:
            continue
        if len(window_files) < int(args.window_len):
            window_files = window_files + [window_files[-1]] * (int(args.window_len) - len(window_files))

        if depth_files is not None and len(depth_files) > 0:
            depth_window = _slice_by_id_or_index(depth_files, window_start, window_end)
            if not depth_window:
                depth_window = [depth_files[min(max(window_start, 0), len(depth_files) - 1)]]
            if len(depth_window) < len(window_files):
                depth_window = depth_window + [depth_window[-1]] * (len(window_files) - len(depth_window))
        else:
            # If no depth is provided, we can't build a valid union control latent; skip.
            if depth_files is not None and len(depth_files) == 0:
                logger.warning("Empty depth dir for %s (street=%s); skip clip", clip_dir, street_name)
            continue

        needed = clip_start + int(args.clip_length)
        if needed > len(window_files):
            window_files = window_files + [window_files[-1]] * (needed - len(window_files))
        if needed > len(depth_window):
            depth_window = depth_window + [depth_window[-1]] * (needed - len(depth_window))

        rgb_paths = window_files[clip_start:clip_start + int(args.clip_length)]
        depth_paths = depth_window[clip_start:clip_start + int(args.clip_length)]

        mask_dir = clip_dir / "mask"
        if not mask_dir.is_dir():
            continue
        mask_files_map: dict[int, Path] = {}
        for p in mask_dir.iterdir():
            if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp") and p.stem.isdigit():
                mask_files_map[int(p.stem)] = p
        if not mask_files_map:
            continue
        mask_paths = _pick_indexed_files(mask_files_map, int(args.clip_length))

        masked_rgb_dir = clip_dir / "masked_rgb"
        masked_rgb_paths: list[Path] | None = None
        if masked_rgb_dir.is_dir():
            mr_map: dict[int, Path] = {}
            for p in masked_rgb_dir.iterdir():
                if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp") and p.stem.isdigit():
                    mr_map[int(p.stem)] = p
            if mr_map:
                masked_rgb_paths = _pick_indexed_files(mr_map, int(args.clip_length))
        if bool(args.require_masked_rgb) and masked_rgb_paths is None:
            continue

        normal_paths: list[Path] | None = None
        # Priority 1: normal under the clip directory.
        local_normal_dir = clip_dir / "normal"
        if local_normal_dir.is_dir():
            n_map: dict[int, Path] = {}
            for p in local_normal_dir.iterdir():
                if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp") and p.stem.isdigit():
                    n_map[int(p.stem)] = p
            if n_map:
                normal_paths = _pick_indexed_files(n_map, int(args.clip_length))

        # Priority 2: external normal_root.
        if normal_paths is None and normal_root is not None:
            # 2a) Mirrored clip hierarchy:
            #   <normal_root>/<street>/<window>/<clip>/normal/*.png
            # or
            #   <normal_root>/<street>/<window>/<clip>/*.png
            ext_dir_1 = normal_root / street_name / window_dir.name / clip_dir.name / "normal"
            ext_dir_2 = normal_root / street_name / window_dir.name / clip_dir.name
            for ext_dir in (ext_dir_1, ext_dir_2):
                if not ext_dir.is_dir():
                    continue
                n_map: dict[int, Path] = {}
                for p in ext_dir.iterdir():
                    if p.is_file() and p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".webp") and p.stem.isdigit():
                        n_map[int(p.stem)] = p
                if n_map:
                    normal_paths = _pick_indexed_files(n_map, int(args.clip_length))
                    break

            # 2b) MatrixCity sequence hierarchy:
            #   <normal_root>/small_city_normal/street/<split>/<street>_normal/<street>_normal/*.png
            #   <normal_root>/small_city_normal/street/<split>/<street>/<street>/*.png
            # and the same patterns when --normal_root already points to small_city_normal.
            if normal_paths is None:
                normal_dir_candidates = [
                    normal_root / "small_city_normal" / "street" / str(args.street_split) / f"{street_name}_normal" / f"{street_name}_normal",
                    normal_root / "small_city_normal" / "street" / str(args.street_split) / street_name / street_name,
                    normal_root / "street" / str(args.street_split) / f"{street_name}_normal" / f"{street_name}_normal",
                    normal_root / "street" / str(args.street_split) / street_name / street_name,
                    normal_root / f"{street_name}_normal" / f"{street_name}_normal",
                    normal_root / street_name / street_name,
                ]
                for nd in normal_dir_candidates:
                    if not nd.is_dir():
                        continue
                    nfiles = _sorted_pngs(nd)
                    if not nfiles:
                        continue
                    normal_window = _slice_by_id_or_index(
                        nfiles, window_start, window_end)
                    if not normal_window:
                        continue
                    if len(normal_window) < len(window_files):
                        normal_window = normal_window + [normal_window[-1]] * (
                            len(window_files) - len(normal_window))
                    needed_n = clip_start + int(args.clip_length)
                    if needed_n > len(normal_window):
                        normal_window = normal_window + [normal_window[-1]] * (
                            needed_n - len(normal_window))
                    normal_paths = normal_window[clip_start:clip_start +
                                                 int(args.clip_length)]
                    break

        if bool(args.require_normal) and normal_paths is None:
            continue

        embeds_list = text_stage.encode_text(
            prompt,
            fastvideo_args=fastvideo_args,
            encoder_index=0,
            return_attention_mask=False,
            return_type="list",
            device=device,
            dtype=torch.float32,
        )
        text_emb = embeds_list[0]
        if text_emb.ndim == 3:
            text_emb = text_emb[0]
        text_emb = text_emb.detach().to("cpu", dtype=torch.float32).numpy()

        if str(args.first_frame_source) == "masked_rgb":
            if masked_rgb_paths is None:
                # Only possible when require_masked_rgb is False.
                first_rgb = _load_rgb_frame(rgb_paths[0], int(args.max_height), int(args.max_width))
            else:
                first_rgb = _load_rgb_frame(masked_rgb_paths[0], int(args.max_height), int(args.max_width))
        else:
            first_rgb = _load_rgb_frame(rgb_paths[0], int(args.max_height), int(args.max_width))
        first_bcthw = _to_vae_input(first_rgb[None, ...], normalize=True).to(device=device, dtype=torch.float32)
        first_lat = _encode_video_latents(vae, first_bcthw, sample_mode="mode")
        if latent_repeat != 1:
            first_lat = first_lat.repeat(1, latent_repeat, 1, 1, 1)
        first_lat = first_lat[0, :, 0].unsqueeze(0)
        first_lat_np = first_lat.to("cpu", dtype=torch.float32).numpy()

        depth_tchw = _load_depth_sequence(
            depth_paths,
            int(args.max_height),
            int(args.max_width),
            pmin=float(args.depth_percentile_min),
            pmax=float(args.depth_percentile_max),
        )
        mask_tchw = torch.stack(
            [
                _load_mask_frame(
                    p,
                    int(args.max_height),
                    int(args.max_width),
                    threshold=None if float(args.mask_threshold) < 0 else float(args.mask_threshold),
                )
                for p in mask_paths
            ],
            dim=0,
        )
        rgb_tchw = None
        if masked_rgb_paths is not None:
            masked_rgb_tchw = torch.stack([_load_rgb_frame(p, int(args.max_height), int(args.max_width)) for p in masked_rgb_paths], dim=0)
        else:
            if bool(args.require_masked_rgb):
                continue
            rgb_tchw = torch.stack([_load_rgb_frame(p, int(args.max_height), int(args.max_width)) for p in rgb_paths], dim=0)
            masked_rgb_tchw = rgb_tchw * mask_tchw
        normal_tchw = None
        if normal_paths is not None:
            normal_tchw = torch.stack(
                [_load_rgb_frame(p, int(args.max_height), int(args.max_width)) for p in normal_paths],
                dim=0,
            )

        vae_lat_np = None
        if bool(args.write_vae_latent):
            if rgb_tchw is None:
                rgb_tchw = torch.stack(
                    [
                        _load_rgb_frame(
                            p, int(args.max_height), int(args.max_width)
                        )
                        for p in rgb_paths
                    ],
                    dim=0,
                )
            rgb_bcthw = _to_vae_input(rgb_tchw, normalize=True).to(
                device=device, dtype=torch.float32
            )
            vae_lat = _encode_video_latents(vae, rgb_bcthw, sample_mode="mode")
            # Keep standard latent channels (z_dim) for main transformer input.
            vae_lat_np = vae_lat[0].to("cpu", dtype=torch.float32).numpy()

        if normal_tchw is not None:
            video_n = torch.cat(
                [
                    _to_vae_input(depth_tchw, normalize=False),
                    # Keep consistent with existing union preprocess in repo.
                    _to_vae_input(normal_tchw, normalize=False),
                    _to_vae_input(masked_rgb_tchw, normalize=True),
                    _to_vae_input(mask_tchw, normalize=False),
                ],
                dim=0,
            ).to(device=device, dtype=torch.float32)
            lat_n = _encode_video_latents(vae, video_n, sample_mode="mode").to(
                "cpu", dtype=torch.float32
            )
            depth_lat = lat_n[0]
            normal_lat = lat_n[1]
            masked_lat = lat_n[2]
            mask_lat = lat_n[3]
        else:
            video_n = torch.cat(
                [
                    _to_vae_input(depth_tchw, normalize=False),
                    _to_vae_input(masked_rgb_tchw, normalize=True),
                    _to_vae_input(mask_tchw, normalize=False),
                ],
                dim=0,
            ).to(device=device, dtype=torch.float32)
            lat_n = _encode_video_latents(vae, video_n, sample_mode="mode").to(
                "cpu", dtype=torch.float32
            )
            depth_lat = lat_n[0]
            masked_lat = lat_n[1]
            mask_lat = lat_n[2]
        if latent_repeat != 1:
            depth_lat = depth_lat.repeat(latent_repeat, 1, 1, 1)
            if normal_tchw is not None:
                normal_lat = normal_lat.repeat(latent_repeat, 1, 1, 1)
            masked_lat = masked_lat.repeat(latent_repeat, 1, 1, 1)
            mask_lat = mask_lat.repeat(latent_repeat, 1, 1, 1)
        if normal_tchw is not None:
            control_lat = torch.cat([depth_lat, normal_lat, masked_lat, mask_lat], dim=0)
        else:
            control_lat = torch.cat([depth_lat, masked_lat, mask_lat], dim=0)
        control_lat_np = control_lat.numpy()

        empty_lat = np.zeros((0,), dtype=np.float32)
        record_id = f"{street_name}/{window_dir.name}/{clip_dir.name}"
        if bool(args.skip_existing_ids) and record_id in existing_ids:
            continue
        record = {
            "id": record_id,
            "text_embedding_bytes": text_emb.tobytes(),
            "text_embedding_shape": list(text_emb.shape),
            "text_embedding_dtype": "float32",
            "vae_latent_bytes": (vae_lat_np.tobytes() if vae_lat_np is not None else empty_lat.tobytes()),
            "vae_latent_shape": (list(vae_lat_np.shape) if vae_lat_np is not None else []),
            "vae_latent_dtype": ("float32" if vae_lat_np is not None else ""),
            "first_frame_latent_bytes": first_lat_np.tobytes(),
            "first_frame_latent_shape": list(first_lat_np.shape),
            "first_frame_latent_dtype": "float32",
            "control_latent_bytes": control_lat_np.tobytes(),
            "control_latent_shape": list(control_lat_np.shape),
            "control_latent_dtype": "float32",
            "file_name": record_id,
            "caption": prompt,
            "media_type": "video",
            "width": int(args.max_width),
            "height": int(args.max_height),
            "num_frames": int(control_lat_np.shape[1]) if len(control_lat_np.shape) > 1 else 0,
            "duration_sec": float(int(args.clip_length)) / float(args.fps) if int(args.fps) > 0 else 0.0,
            "fps": float(args.fps),
        }
        buffer.append(record)
        written_count += 1
        if bool(args.skip_existing_ids):
            existing_ids.add(record_id)

        if len(buffer) >= int(args.flush_frequency):
            table = records_to_table(buffer, pyarrow_schema_ti2v_controlnet)
            writer.append_table(table)
            writer.flush(num_workers=1, write_remainder=False)
            buffer = []

        if int(args.max_samples) > 0 and written_count >= int(args.max_samples):
            logger.info(
                "Reached max_samples=%d on rank_%02d, stopping early.",
                int(args.max_samples),
                int(args.rank),
            )
            break

    if buffer:
        table = records_to_table(buffer, pyarrow_schema_ti2v_controlnet)
        writer.append_table(table)
        writer.flush(num_workers=1, write_remainder=True)

    logger.info("Done. Wrote parquet dataset to: %s (rank shard: %s)", output_dir, out_dir_rank)


if __name__ == "__main__":
    main()
